let parcela1 = 15
let parcela2 = 20
let resultado = 0
var parcela3 = 150
var parcela4 = 200
var resultado2 = 0
let meu_nome = "Emilly"
var meu_nome2 = "Emilly Fernandes Alves de Souza"
let parcelaJunta = parcela1